# Elasticsearch 공식 이미지를 베이스로 사용
FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.0

# 환경 변수 설정
# Elasticsearch를 단일 노드 모드로 실행, ENV 명령어는 Elasticsearch 설정을 위한 환경 변수를 설정합니다. discovery.type=single-node는 Elasticsearch를 클러스터 모드가 아닌 단일 노드 모드에서 실행하도록 설정하는 데 사용됩니다.
ENV discovery.type=single-node

# Elasticsearch의 포트 9200 (HTTP) 및 9300 (TCP)을 노출
EXPOSE 9200 9300

# Elasticsearch 실행 커맨드를 기본값으로 설정
CMD ["eswrapper"]
